<script>
  import _ from "lodash-es";

  import { Binary, QrCode, Phone, Fingerprint } from "lucide-svelte";

  export let auth;
</script>

<div class="bg-base-100 rounded-lg p-3">
  <div class="flex items-center gap-3 pl-1.5">
    <QrCode size="30" />

    <div class="grow">
      <div class="font-bold">Authenticator app</div>
      <p class="text-xs">Enter one-time codes generated by an app.</p>
    </div>

    <button class="btn"> enable </button>
  </div>
</div>
