<script>
  import _ from "lodash-es";
  import * as OTPAuth from "otpauth";
  import { QRCodeImage as QrCode } from "svelte-qrcode-image";

  import {
    X,
    Check,
    Clock,
    Trash2 as Trash,
    MessageSquare,
    Binary,
    QrCode as Icon,
    Phone,
    Fingerprint,
    AlertTriangle,
  } from "lucide-svelte";

  import Card from "./Card.svelte";
  import PasswordInput from "./PasswordInput.svelte";
  import PhoneInput from "./PhoneInput.svelte";
  import CodeInput from "./CodeInput.svelte";
  import Time from "./Time.svelte";
  import Alert from "./Alert.svelte";

  export let auth;
  export let authorize;

  let resetOTP = () => {
    return new OTPAuth.TOTP({
      issuer: auth.settings.name,
      label: auth.actor.identifier,
      secret: new OTPAuth.Secret(),
    });
  };

  let totp = resetOTP();
  let adding;
  let verifying;
  let otpSecret;
  let showSecret;
  let code;
  let validCode;
  let empty;

  $: empty = !auth?.actor?.otpSecrets?.length;

  let debounceName = _.debounce((id, name) => {
    authorize({ event: "totp:name", updates: { name, id } });
  }, 300);

  let updateName = (id) => {
    return (e) => {
      debounceName(id, e.target.value);
    };
  };

  let debounceAdd = _.debounce(() => {
    if (!validCode || !code) {
      return;
    }

    authorize({
      event: "totp:add",
      updates: { secret: totp.secret.base32, code },
    }).then((result) => {
      code = null;

      if (!result?.warnings?.length) {
        totp = resetOTP();
        adding = false;
      }
    });
  }, 100);

  $: if (validCode && !verifying) {
    debounceAdd(totp.secret.base32, code);
  }
</script>

<Card>
  <div class="flex items-center gap-1.5 py-1">
    <Icon size="16" />

    <div class="grow">
      <div class="text-xs font-bold">Authenticator app</div>
    </div>
  </div>

  {#if empty && !verifying && !adding}
    <div class="text-sm opacity-75 mb-3">
      Use one-time passwords from an authenticator app.
    </div>
  {/if}

  <div class="flex flex-col gap-1.5 my-1.5">
    {#if auth?.actor?.otpSecrets?.length}
      {#each auth?.actor?.otpSecrets || [] as otpSecret}
        <div class="flex items-center gap-3">
          <label
            class="grow flex items-center gap-3 w-full input input-sm px-1.5 h-[35px]"
          >
            <input
              class="w-full pl-1.5 text-base dark:text-white text-black placeholder:text-sm"
              placeholder="Enter a name for this authenticator..."
              value={otpSecret.name}
              on:input={updateName(otpSecret.id)}
            />
            <span class="text-xs whitespace-nowrap text-base-content opacity-75"
              ><Time ago="old" timestamp={otpSecret.createdAt} /></span
            >
            <button type="button" class="btn btn-xs text-error m-0 p-0 px-1">
              <Trash size="14" />
            </button>
          </label>
        </div>
      {/each}
    {/if}
  </div>

  {#if adding}
    <div class="mb-3 bg-base-100 p-3 px-4 rounded-lg">
      <div class="flex items-start gap-3 mb-3">
        <p class="text-sm">
          <b>Step one:</b> Scan the following QR code in your authenticator app.
          You can also enter the secret manually:
        </p>

        <button
          type="button"
          on:click|preventDefault|stopPropagation={() => (adding = false)}
          class="btn btn-sm px-1"><X /></button
        >
      </div>

      <QrCode
        text={totp.toString()}
        displayClass="mb-1.5 w-full h-full max-w-[250px] mx-auto rounded"
        width="5"
      />

      <div class="max-w-[250px] mx-auto">
        {#if showSecret}
          <PasswordInput
            disabled
            value={totp.secret.base32}
            class="input-sm ml-0"
          />
        {:else}
          <button
            type="button"
            class="btn btn-link w-full text-center !text-base-content opacity-75 btn-sm"
            on:click|preventDefault|stopPropagation={() => (showSecret = true)}
            >show secret</button
          >
        {/if}
      </div>

      <div class="divider mb-1.5 mt-0" />

      <p class="text-sm mb-1.5">
        <b>Step two:</b>
        Enter the 6-digit code generated by your authenticator app:
      </p>

      <CodeInput
        {auth}
        length={6}
        bind:value={code}
        bind:complete={validCode}
      />
    </div>
  {:else}
    <button
      type="button"
      class="btn btn-sm w-full"
      on:click|preventDefault|stopPropagation={() => (adding = true)}
    >
      {#if empty}
        add an authenticator
      {:else}
        add another authenticator
      {/if}
    </button>
  {/if}
</Card>
