integration: &integration
  email: "<%= ENV['MASKS_EMAIL_INTEGRATION'] || 'smtp' %>"
  phone: "<%= ENV['MASKS_PHONE_INTEGRATION'] || 'twilio' %>"
  storage: "<%= ENV['MASKS_STORAGE_INTEGRATION'] || 'disk' %>"
  sendmail: {}
  smtp:
    address: <%= ENV['MASKS_SMTP_ADDRESS'] %>
    port: <%= ENV['MASKS_SMTP_PORT'] %>
    domain: <%= ENV['MASKS_SMTP_DOMAIN'] %>
    user_name: <%= ENV['MASKS_SMTP_USER_NAME'] %>
    password: <%= ENV['MASKS_SMTP_PASSWORD'] %>
    authentication: <%= ENV['MASKS_SMTP_AUTHENTICATION'] %>
  twilio:
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    service_sid: <%= ENV['TWILIO_SERVICE_SID'] %>
  disk:
    root: "<%= ENV['MASKS_STORAGE_DIR'] || Rails.root.join('data', 'storage') %>"
  s3:
    access_key_id: <%= ENV['MASKS_S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['MASKS_S3_SECRET_ACCESS_KEY'] %>
    region: <%= ENV['MASKS_S3_REGION'] %>
    bucket: <%= ENV['MASKS_S3_BUCKET'] %>
  gcs:
    project: <%= ENV['MASKS_GCS_PROJECT'] %>
    credentials: <%= ENV['MASKS_GCS_CREDENTIALS'] %>
    bucket: <%= ENV['MASKS_GCS_BUCKET'] %>
  azure_storage:
    storage_account_name: <%= ENV['MASKS_AZURE_STORAGE_ACCOUNT_NAME'] %>
    storage_access_key: <%= ENV['MASKS_AZURE_STORAGE_ACCESS_KEY'] %>
    container: <%= ENV['MASKS_AZURE_STORAGE_CONTAINER'] %>

default: &default
  url: "<%= ENV['MASKS_URL'] || 'http://localhost:1111' %>"
  name: "<%= ENV['MASKS_NAME'] || 'masks' %>"
  timezone: "<%= ENV['MASKS_TZ'] || 'America/New_York' %>"
  region: "<%= ENV['MASKS_REGION'] || 'US' %>"
  private_key: "<%= ENV['MASKS_PRIVATE_KEY'] || Rails.root.join('data', 'private.key') %>"
  seeds_dir: "<%= ENV['MASKS_SEEDS_DIR'] %>"
  db:
    adapter: <%= ENV['MASKS_DB_ADAPTER'] %>
    name: <%= ENV['MASKS_DB_NAME'] %>
    url: <%= ENV['MASKS_DB_URL'] %>
  redis:
    url: "<%= ENV['REDIS_URL'] %>"
  theme:
    name: "<%= ENV['MASKS_NAME'] || 'masks' %>"
  checks:
    - device
    - credentials
    - second-factor
    - client-consent
    - onboarded
    - verified-email
  prompts:
    - Masks::Prompts::Device
    - Masks::Prompts::Identifier
    - Masks::Prompts::LoginLink
    - Masks::Prompts::Password
    - Masks::Prompts::Credentials
    - Masks::Prompts::Phone
    - Masks::Prompts::Webauthn
    - Masks::Prompts::Totp
    - Masks::Prompts::BackupCode
    - Masks::Prompts::SecondFactor
    - Masks::Prompts::ResetPassword
    - Masks::Prompts::Onboard
    - Masks::Prompts::VerifyEmail
    - Masks::Prompts::OIDC
    - Masks::Prompts::InternalSession
    - Masks::Prompts::LastLogin
  manager:
    nickname: "<%= ENV['MASKS_MANAGER_NICKNAME'] || 'manager' %>"
    password: "<%= ENV['MASKS_MANAGER_PASSWORD'] %>"
    email: "<%= ENV['MASKS_MANAGER_EMAIL'] %>"
  secret_key: "<%= ENV['MASKS_SECRET_KEY']  %>"
  encryption_key: "<%= ENV['MASKS_ENCRYPTION_KEY'] %>"
  deterministic_key: "<%= ENV['MASKS_DETERMINISTIC_KEY'] %>"
  salt: "<%= ENV['MASKS_SALT'] %>"
  clients:
    types:
      - internal
      - public
      - confidential
    scopes:
      required: []
      allowed: []
    checks:
      - device
      - credentials
    subject_types:
      - public-uuid
      - public-identifier
      - pairwise-uuid
    client_type: internal
    subject_type: pairwise-uuid
    id_token_expires_in: "6 hours"
    access_token_expires_in: "6 hours"
    code_expires_in: "10 minutes"
    refresh_expires_in: "1 month"
    login_link_expires_in: "10 minutes"
    auth_attempt_expires_in: "1 hour"
    login_link_factor_expires_in: "12 hours"
    password_factor_expires_in: "1 day"
    second_factor_backup_code_expires_in: "1 hour"
    second_factor_sms_code_expires_in: "10 minutes"
    second_factor_totp_code_expires_in: "10 minutes"
    second_factor_webauthn_expires_in: "10 minutes"
    email_verification_expires_in: "1 year"
    internal_session_expires_in: "1 day"
    allow_passwords: true
    allow_login_links: true
    autofill_redirect_uri: false
    bg_dark: |
      background: radial-gradient(
        circle,
        rgba(62, 65, 55, 1) 0%,
        rgba(54, 47, 40, 1) 25%,
        rgba(31, 41, 55, 1) 50%,
        rgba(10, 8, 14, 1) 100%
      );
    bg_light: |
      background: radial-gradient(
        circle,
        #00cdb7,
        #00c6d2,
        #00bcea,
        #00b0fb,
        #009fff,
        #2e8eef,
        #407dde,
        #4c6ccc,
        #365ca5,
        #294b7f,
        #233a5a,
        #1f2937
      );
  totp_codes:
    enabled: true
  sms_codes:
    enabled: true
  passkeys:
    enabled: true
  webauthn:
    enabled: true
  backup_codes:
    min_chars: 8
    max_chars: 100
    total: 10
  login_links:
    enabled: true
  passwords:
    min_chars: 8
    max_chars: 100
    change_cooldown: "15 minutes"
  nicknames:
    enabled: true
  emails:
    enabled: true
    max_for_login: 5
  integration:
    <<: *integration

development:
  <<: *default
  url: "http://localhost:1111"
  private_key: "<%= Rails.root.join('config', 'private.development.key') %>"
  integration:
    <<: *integration
    email: "dev"
    storage: "disk"
  manager:
    nickname: manager
    email: masks@example.com
    password: password

test:
  <<: *default
  url: "http://localhost:1111"
  private_key: "<%= Rails.root.join('config', 'private.test.key') %>"
  manager:
    nickname: manager
    email: masks@example.com
    password: password
  integration:
    <<: *integration
    email: "test"
    storage: "disk"
    phone: "test"

production:
  <<: *default
