default: &default
  "openid": "Your unique account identifier"
  "email": "Your email address"
  "nickname": "Your nickname"
  "name": "Your full name"
  "profile": "Your profile—including name and email"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
