name: "CI"
on:
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install node and deps
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 21
      - run: npm install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install node and deps
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 21
      - run: npm install
      - name: Security audit dependencies
        run: bundle exec bundle-audit check --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint files
        run: npm run lint
