on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      # The name of your gem/package.
      GEM_NAME: "masks"
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
        if: ${{ steps.release.outputs.release_created }}
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
        if: ${{ steps.release.outputs.release_created }}
      - run: gem build masks.gemspec
        if: ${{ steps.release.outputs.release_created }}
      - run: gem install ./masks-*.gem
        if: ${{ steps.release.outputs.release_created }}
      - run: gem push ./masks-*.gem
        if: ${{ steps.release.outputs.release_created }}
