on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      # The name of your gem/package.
      GEM_NAME: "masks"
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
        if: ${{ steps.release.outputs.release_created }}
      - name: setup ruby
        uses: ruby/setup-ruby@v1.148.0
        with:
          ruby-version: 3.1.4
        if: ${{ steps.release.outputs.release_created }}
      - name: checkout code
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
        if: ${{ steps.release.outputs.release_created }}
      - name: publish gem
        run: |
          bundle config unset deployment
          bundle install
          gem build *.gemspec
          gem push *.gem
        if: ${{ steps.release.outputs.release_created }}
